### ISSUE TITLE
Can we use this with the codeclimate.com service?

### ISSUE THREAD

**Issue by seanculver** [fazibear/codeclimate-elixir#1]
Hey, thanks for putting this together. Will this work on the codeclimate.com service? If not, is there anything I can do to get this through the QA / submission process?

**Comment by fazibear** [comment]
This repo is deprecated. It was a bad idea to make a single engine for elixir. I decided to split things. Please check:

 - [Code Climate Credo Engine](https://github.com/fazibear/codeclimate-credo)
 - [Code Climate Dogma Engine](https://github.com/fazibear/codeclimate-dogma)

In the future this engine will check your code using elixir compiler. Stay tuned.
